export const theme = {
    color: {
        black: "#000",
        silver: "#656565",
        alto: "#eaeaea",
        gallery: "#eee",
        navigation: "#fff",
        background: "#fff",
        search: "#ffffffc7",
        sectionShadow: "#eaeaea",
        section: "#fff",
        font: "#1d4368",
        fontOnButton: "#fff",
        white: "#fff",
        teal: "#1d4368",
        footerBackground: "#183a5a",
        tableBackgroud: "#f8f7f7",
        tableHeader: "#c0c0c0",
        tableBorder: "#d9d9d9",
        tableHover: "#eeeeee",
        hoursBorder: "#eaeaea",
        lessImportant: "#808080",
        brigtherLessImportant: "#f3f3f3",
        crimson: "#a91818",
        forestGreen: "#228c22",
    },
    breakpoint: {
        mobileMax: 1050,
        mobileMax2: 820,
        mobileMax3: 304,
    },
};